---
- name: Check if kernel headers exist for {{ item }}
  stat:
    path: /lib/modules/{{ item }}
  register: file_details

- name: Configure module for kernel {{ item }}
  shell:
    cmd: bash ./build.sh --configure-only --kver={{ item }}
    chdir: "{{ nocreate_build_dir }}"
  when: file_details.stat.exists

- name: "Build, install, and reload for active kernel {{ item }}"
  shell:
    cmd: X4B.FW module install NOCREATE NOCREATEA TCPCREATE TCPCREATEA
    chdir: "{{ nocreate_build_dir }}/src"
  when: file_details.stat.exists and item == ansible_kernel

- name: "Build and install for inactive kernel {{ item }}"
  shell:
    cmd: make install KCFLAGS=-O3
    chdir: "{{ nocreate_build_dir }}/src"
  when: file_details.stat.exists and item != ansible_kernel

- name: Clean build artifacts for kernel {{ item }}
  shell:
    cmd: make clean
    chdir: "{{ nocreate_build_dir }}/src/"
  when: file_details.stat.exists and nocreate_cleanup
