PACKAGE_NAME=xt-nocreate
pushd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null
PACKAGE_VERSION="$(./version.sh)"
popd >/dev/null
BUILT_MODULE_NAME[0]=xt_NOCREATE
DEST_MODULE_LOCATION[0]=/kernel/extra
STRIP[0]=no
MAKE[0]="make xt_NOCREATE.ko"
PRE_BUILD="./configure --from-dkms-conf=$kernel_source_dir"
AUTOINSTALL=yes
